### ISSUE TITLE
Wifi Shield?

### ISSUE THREAD

**Issue by shakesomedust** [exciting-io/printer#48]
Would it be possible to use a WiFi shield instead of an ethernet one?

http://www.amazon.com/Arduino-WiFi-Shield/dp/B009M8BU50

Thoughts?

**Comment by mungle** [comment]
What about ESP8266?

**Comment by lazyatom** [comment]
I can't comment specifically about different chipsets because I don't really have any experience with them; all I can sensibly say is that the hardware you use doesn't really matter, as long as it comes with Arduino-compatible libraries (if you want to try to re-use the existing sketch), or if you're comfortable adapting the code yourself.

Hope that helps!
