### ISSUE TITLE
unexpted tLABEL

### ISSUE THREAD

**Issue by JDHE** [exciting-io/printer#54]
Getting this error when I try to start up the client. Any ideas?
```
./pi-printer.rb:15: syntax error, unexpected tLABEL, expecting ')'
  def initialize(serial_port: "/dev/ttyAMA0")
                             ^
./pi-printer.rb:15: syntax error, unexpected ')', expecting keyword_end
./pi-printer.rb:137: syntax error, unexpected keyword_end, expecting $end
```

**Comment by lazyatom** [comment]
What version of ruby do you have?

**Comment by JDHE** [comment]
I was getting /var/lib/gems permission issues when I tried to use the system Ruby (on the current Raspbian release on a Pi Zero). So I installed RVM and it installed ruby 1.9.3-p484 per the ruby-version file. I really want to get this to work. I have the printer working via serial using other methods like python, minicom, CUPS.  I checked /dev/ttyAMA0 every possible way,  /boot/cmdline.txt looks good, so it should be available.  

Is it having an issue with serial_port? I don't have the TX from the printer connected to the rPi because I thought it wasn't necessary (since we are  just trying to get the printer to RX). Could that be the issue?

I'm just not familiar enough with Ruby to understand what's causing this.  Thanks for the response.

**Comment by lazyatom** [comment]
Short version: apologies, this is my fault, please pull, use RVM to install Ruby 2.3 (in the now-updated `.ruby-version`), run `bundle install` and try again.

Less-short version: 

The error is caused because of a syntax change that's allowed in Ruby 2+, but not 1.9.3 (it's the `serial_port:` named keyword argument part). However, this is totally my fault - the *server* was developed against an earlier version of Ruby, but the raspberry pi script around a different one.

Sorry about that!

**Comment by JDHE** [comment]
Ha ha, and here I was telling myself it must be my own stupid noob problem. I will try it tonight! Thanks for the help!!
